services:
  #web01:
    #build: 
      #context: ./web01
      #dockerfile: Dockerfile
    #container_name: web01
    #ports:
      #- "80:80/tcp"
  web02:
    build:
      context: ./web02
      dockerfile: Dockerfile
    container_name: web02
    ports:
      - "80:80/tcp"
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"  